[env:uno-dht22]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    winlinvip/SimpleDHT@^1.0.15
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
monitor_speed = 9600
upload_speed = 115200

[env:uno-sht31]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    adafruit/Adafruit SHT31 Library@^2.2.1
    LiquidCrystal
monitor_speed = 9600
upload_speed = 115200

[env:lcd-test]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
monitor_speed = 9600
upload_speed = 115200
build_src_filter = +<diag.cpp>

[env:uno-wokwi]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    robtillaart/SHT31_SW@^0.3.2
    stevemarple/SoftWire@^2.0.10
    winlinvip/SimpleDHT@^1.0.15
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
monitor_speed = 9600
upload_speed = 115200

[env:i2c-wokwi]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    adafruit/Adafruit SHT31 Library@^2.2.1
    winlinvip/SimpleDHT@^1.0.15
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
monitor_speed = 9600
upload_speed = 115200
